[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E293B"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#F1F5F9"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
